version: 0.0
os: linux
files:
  - source: dotnetLexChatBot/build_output
    destination: /opt/codedeploy-agent/deployment-root/119caa4a-0416-4773-83f1-200b1698e3d7/d-CW8BLA2WM/deployment-archive/
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/aspnetlexchatbot
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
